on: [push]

jobs:
  test-conftest:
    env:
      GITHUB_TOKEN: ${{ secrets.TOKEN }}
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Get binary
      uses: dsaltares/fetch-gh-release-asset@master
      with:
        repo: "loveholidays/action-conftest"
        version: "latest"
        file: "action-conftest"
        token: ${{ secrets.TOKEN }}
        
    - name: Check the binary
      run: |
        ls -lah