on: [push]

jobs:
  test-conftest:
    env:
      GITHUB_TOKEN: ${{ secrets.TOKEN }}
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Get binary
      uses: dsaltares/fetch-gh-release-asset@master
      with:
        repo: "loveholidays/action-conftest"
        version: "latest"
        file: "action-conftest"
        token: ${{ secrets.TOKEN }}
    
    - name: Prepare all binaries
      run: |
        sudo chown runner:docker action-conftest
        sudo chmod +x action-conftest
        sudo mv action-conftest /usr/local/bin

        wget https://github.com/open-policy-agent/conftest/releases/download/v0.22.0/conftest_0.22.0_Linux_x86_64.tar.gz
        tar xzf conftest_0.22.0_Linux_x86_64.tar.gz conftest
        sudo mv conftest /usr/local/bin
        rm -f conftest_0.22.0_Linux_x86_64.tar.gz

        curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash
        sudo mv kustomize /usr/local/bin
    - name: Run tests
      run: |
        action-conftest -env=development-eu -kustomize=true -overlays=kustomization/overlays -policy=kubernetes