on: [push]

jobs:
  test-conftest:
    env:
      GITHUB_TOKEN: ${{ secrets.TOKEN }}
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Get binary
      run: |
        wget https://github.com/loveholidays/action-conftest/releases/download/0.3/action-conftest
    - name: Check the binary
      run: |
        ls -lah